# Generated by Django 4.1.13 on 2026-04-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPISnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rgr', models.FloatField(verbose_name='Revenue Growth Rate')),
                ('itr', models.FloatField(verbose_name='Inventory Turnover Ratio')),
                ('er', models.FloatField(verbose_name='Expense Ratio')),
                ('scp', models.FloatField(verbose_name='Stock Coverage Period')),
                ('bhs', models.FloatField(verbose_name='Business Health Score')),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
