# Generated by Django 4.1.13 on 2026-04-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_kpisnapshot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpisnapshot',
            name='report_type',
            field=models.CharField(default='Monthly', max_length=20, verbose_name='Report Period'),
        ),
    ]
