# Generated by Django 4.1.13 on 2026-04-30 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_kpisnapshot_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpisnapshot',
            name='net_profit',
            field=models.FloatField(default=0.0, verbose_name='Net Profit'),
        ),
        migrations.AddField(
            model_name='kpisnapshot',
            name='total_expenses',
            field=models.FloatField(default=0.0, verbose_name='Total Expenses'),
        ),
        migrations.AddField(
            model_name='kpisnapshot',
            name='total_revenue',
            field=models.FloatField(default=0.0, verbose_name='Total Revenue'),
        ),
        migrations.CreateModel(
            name='StoreIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='My Store', max_length=255)),
                ('store_url', models.URLField(help_text='e.g. http://localhost:3001/orders')),
                ('api_key', models.CharField(help_text='Your secret API Key', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_integration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
