# Generated by Django 4.1.13 on 2026-04-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_kpisnapshot_net_profit_kpisnapshot_total_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeintegration',
            name='platform_type',
            field=models.CharField(choices=[('custom', 'Custom API (WonderToyz / JSON Server)'), ('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('daraz', 'Daraz')], default='custom', max_length=20),
        ),
    ]
